language: python

python:
  - "2.7"

sudo: true

# command to install dependencies
install: make install_requirements_no_vnenv

# command to run tests
script: make test_no_venv

after_success: make auto-merge
