language: python
python:
  - "2.7"

env: TRAVIS_COMMIT_MESSAGEE="%{commit_message}"

# command to install dependencies
install: make install-requirements

# command to run tests
script: make test

script: cd gestion_tfg && python manage.py test

after_success: cd .. && make auto-merge
