language: python
python:
  - "2.7"

env: TRAVIS_COMMIT_MESSAGE=commit_message

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script: cd gestion_tfg && python manage.py test

after_success: cd .. && make auto-merge
